variable "aws_region" {
  default = "us-west-1" # California (test region)
}

variable "ami_os" {
  default = "ami-0ad16744583f21877" #for us-west-1 - California (Ubuntu 16.04)
}

variable "terraform-user" {
  default     = "ubuntu"
  description = "User that is ssh-ing into EC2"
}

variable "public_key_value" {
  default     = "define_here_public_key_value"
  description = "Define public key value"
}

variable "vpc_entire_cidr" {
  default     = "10.0.0.0/16"
  description = "Generated by Terraform - Entire CIDR range for entire VPC"
}

variable "allowed_cidr_blocks" {
  default = ["0.0.0.0/0"]
  type    = "list"
}

variable "instance_type" {
  default     = "t2.micro"
  description = "The type of instance to start"
}

variable "autoscaling_group_min_size" {
  default = "2"
}

variable "autoscaling_group_max_size" {
  default = "5"
}

variable "rds_instance_identifier" {
  default = "terraformtestmariadb"
}

variable "database_name" {
  default = "terraform_test_db"
}

variable "database_user" {
  default = "db_username"
}

variable "database_password" {
  default = "db_password"
}
